<div class="row">
    <div class="col-lg-12">
        <h4 class="page-header">
            <span>Gainers</span>
            <a class="pull-right" href="/MarketSummary.aspx?type=gainers">More</a>
        </h4>
        <div class="date-label">
            <span class="label label-default" id="label-gainer-1">As of 2016/11/03 03:00:00</span>
        </div>
        <table data-live-label="#label-gainer-1" data-live-range="5" data-live-summary="true" data-live="gainers" class="table table-hover table-index"><tbody><tr><th>Symbol</th><th>LTP</th><th>% Change</th><th class="hidden">High</th><th class="hidden">Low</th><th class="hidden">Open</th><th>Qty</th><th class="hidden">Turnover</th></tr><tr class="increase"><td><a title="NMBMF (NMB Microfinance Bittiya Sanstha Ltd.)" href="/CompanyDetail.aspx?symbol=NMBMF" target="_blank">NMBMF</a></td><td>1,949.00</td><td>9.99</td><td class="hidden">1,949.00</td><td class="hidden">1,800.00</td><td class="hidden">1,772.00</td><td>2,129</td><td class="hidden">4,087,070.00</td></tr><tr class="increase"><td><a title="JSLBB (Janautthan Samudayic Laghubitta Bikas Bank Ltd.)" href="/CompanyDetail.aspx?symbol=JSLBB" target="_blank">JSLBB</a></td><td>2,965.00</td><td>9.98</td><td class="hidden">2,965.00</td><td class="hidden">2,749.00</td><td class="hidden">2,749.00</td><td>490</td><td class="hidden">1,447,520.00</td></tr><tr class="increase"><td><a title="VSDBL (Vibor Society Development Bank Limited)" href="/CompanyDetail.aspx?symbol=VSDBL" target="_blank">VSDBL</a></td><td>182.00</td><td>8.98</td><td class="hidden">182.00</td><td class="hidden">170.00</td><td class="hidden">170.00</td><td>50</td><td class="hidden">8,800.00</td></tr><tr class="increase"><td><a title="SFFIL (Shrijana Finance (Bittaya Sanstha))" href="/CompanyDetail.aspx?symbol=SFFIL" target="_blank">SFFIL</a></td><td>438.00</td><td>7.88</td><td class="hidden">438.00</td><td class="hidden">414.00</td><td class="hidden">414.00</td><td>60</td><td class="hidden">25,480.00</td></tr><tr class="increase"><td><a title="CBBL (Chhimek Laghubitta Bikas Bank Limited)" href="/CompanyDetail.aspx?symbol=CBBL" target="_blank">CBBL</a></td><td>2,104.00</td><td>7.35</td><td class="hidden">2,115.00</td><td class="hidden">1,999.00</td><td class="hidden">1,999.00</td><td>26,916</td><td class="hidden">55,546,900.00</td></tr></tbody></table>
    </div>
</div>